import { COMPANY_INFO } from "@/shared/constants/company";

export const SERVICES = [
  {
    icon: "globe",
    title: "Recherche personnalisée",
    desc: `Nous recherchons le véhicule adapté à votre budget, votre usage et vos préférences dans notre réseau de ${COMPANY_INFO.stats.countries} pays sources.`,
    features: [
      "Analyse du besoin",
      "Comparaison des options",
      "Sélection selon budget",
      "Devis avant engagement",
    ],
    badge: "Service clé",
    badgeColor: "rgba(201,168,76,0.12)",
    badgeTextColor: "var(--gold)",
    badgeBorderColor: "rgba(201,168,76,0.3)",
  },
  {
    icon: "ship",
    title: "Transport international",
    desc: "Nous coordonnons les étapes logistiques avec les partenaires de transport, du pays d'origine jusqu'à l'arrivée au Congo.",
    features: [
      "Coordination maritime",
      "Suivi des étapes",
      "Documents de transport",
      "Préparation à l'arrivée",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
  {
    icon: "fileCheck",
    title: "Dédouanement",
    desc: "Nous accompagnons les démarches douanières pour clarifier les coûts, les documents nécessaires et les étapes administratives.",
    features: [
      "Préparation du dossier",
      "Estimation des frais",
      "Suivi des formalités",
      "Conseil documentaire",
    ],
    badge: "Accompagnement",
    badgeColor: "rgba(46,204,113,0.1)",
    badgeTextColor: "var(--green)",
    badgeBorderColor: "rgba(46,204,113,0.25)",
  },
  {
    icon: "search",
    title: "Vérification avant achat",
    desc: "Avant validation, nous privilégions les informations utiles: état général, photos, historique disponible et cohérence du prix.",
    features: [
      "Contrôle des informations",
      "Photos et détails",
      "Historique disponible",
      "Points de vigilance",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
  {
    icon: "shield",
    title: "Conseil assurance transit",
    desc: "Nous vous orientons sur les options de protection disponibles pendant le transport selon la valeur et le pays d'origine du véhicule.",
    features: [
      "Options de couverture",
      "Conseil selon valeur",
      "Documents utiles",
      "Aide à la déclaration",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
  {
    icon: "fileText",
    title: "Accompagnement administratif",
    desc: "Nous aidons à anticiper les démarches après importation: documents, mise en circulation et étapes locales à prévoir.",
    features: [
      "Liste des documents",
      "Conseil immatriculation",
      "Préparation dossier",
      "Suivi post-arrivée",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
  {
    icon: "wrench",
    title: "Conseil après livraison",
    desc: "Après réception, nous restons disponibles pour orienter vers les bonnes pratiques d'entretien et les points à vérifier.",
    features: [
      "Conseils d'entretien",
      "Points de contrôle",
      "Orientation technique",
      "Support client",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
  {
    icon: "smartphone",
    title: "Suivi client",
    desc: "Vous gardez un contact clair avec l'équipe pendant le projet, notamment pour les devis, les informations véhicule et les étapes clés.",
    features: [
      "Échanges WhatsApp",
      "Devis lisibles",
      "Mises à jour utiles",
      "Historique des échanges",
    ],
    badge: null,
    badgeColor: "",
    badgeTextColor: "",
    badgeBorderColor: "",
  },
] as const;

export const SERVICE_PROCESS = [
  {
    step: "1",
    title: "Échange initial",
    desc: "Nous clarifions votre besoin, votre budget, vos délais et le type de véhicule recherché.",
  },
  {
    step: "2",
    title: "Recherche & comparaison",
    desc: "Nous identifions les options pertinentes et comparons prix, état, disponibilité et pays d'origine.",
  },
  {
    step: "3",
    title: "Devis transparent",
    desc: "Vous recevez une estimation claire avec les principaux coûts à prévoir.",
  },
  {
    step: "4",
    title: "Validation & achat",
    desc: "Après accord, nous accompagnons la validation du véhicule et la préparation des documents.",
  },
  {
    step: "5",
    title: "Transport & formalités",
    desc: "Nous suivons les étapes logistiques et administratives jusqu'à l'arrivée du véhicule.",
  },
  {
    step: "6",
    title: "Livraison & suivi",
    desc: "Nous restons disponibles après réception pour les dernières démarches et questions pratiques.",
  },
] as const;
